steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/kulwinder-semester2/kulwinder-100931278/lab-02:${SHORT_SHA}', '.']

images:
  - 'us-central1-docker.pkg.dev/kulwinder-semester2/kulwinder-100931278/lab-02:${SHORT_SHA}'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
