steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    args:
      - 'build'
      - '--tag'
      - 'us-central1-docker.pkg.dev/kulwinder-semester2/lab-02/${COMMIT_SHA}'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/kulwinder-semester2/lab-02/${COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

timeout: 1200s  # timeout for the build
